export default {
  XNXX: "https://xnxx.com",
  XVIDEOS: "https://xvideos.com",
  SPANKBANG: "https://spankbang.party",
  XHAMSTER: "https://xhamster.com",
  PORNHUB: "https://pornhub.org",
  EPORNER: "https://eporner.com",
  HENTAIFOX: "https://hentaifox.com",
  XASIAT: "https://xasiat.com",
  HENTAICITY: "https://hentaicity.com",
  JAVHDTODAY: "https://javhd.today",
  JAVTSUNAMI: "https://javtsunami.com",
  JAVGIGA: "https://javgiga.com",
  MISSAV: "https://missav.ws/en",
};
